### ISSUE TITLE
Plushie Buddies [0.1.2][1.20.1]

### ISSUE THREAD

**Issue by taz1009** [Subthy/Subthy-s-mod-issues#1]
**Mod version**
Mod version, game version & modloader
0.1.2, 1.20.1, forge

**Describe the bug**

First launch of the game fisting a tree causing the game to crash, with no crash report.
Second time I changed the logs into planks and then it crashed giving me a report attached.
Sometimes it causes crashing in creative mode when opening the inventory.

**To Reproduce**
Steps to reproduce the behaviour: 

on a server, mine a tree. open inv in creative. make wooden planks.

**Logs & Crash reports**

**_java.lang.NullPointerException: Registry Object not present: plushie_buddies:plushie_dark_father_**
This seems the be the cause of the problem.

https://mclo.gs/GdJtaPU

**Comment by Subthy** [comment]
Mod version mismatch between client and server
